### ISSUE TITLE
Add ISO country code

### ISSUE THREAD

**Issue by WolfgangFahl** [somnathrakshit/geograpy3#10]
returned country information should include the two [letter ISO code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) of the country

**Comment by adriens** [comment]
Hi, would you share a code snippet about this :grey_question: :pray:

**Comment by adriens** [comment]
:point_down: 

- https://github.com/somnathrakshit/geograpy3/issues/24

**Comment by WolfgangFahl** [comment]
Just ask via https://stackoverflow.com/questions/tagged/geograpy
