### ISSUE TITLE
Score for each location?

### ISSUE THREAD

**Issue by 0AlphaZero0** [somnathrakshit/geograpy3#21]
Could it be possible to have a score for each location found?
Indeed sometimes it could be good to know why some locations are in the results for example :
`
>>> import geograpy
>>> places = geograpy.get_geoPlace_context(text="This sentence mention UK as country and London as city.")
>>> places.countries
['United Kingdom', 'United States', 'Canada']
>>> places.cities
['London']
>>> places = geograpy.get_geoPlace_context(text="Jin Yin-tan Hospital, Wuhan, China.")
>>> places.countries
['China', 'Mexico', 'United States']
>>> places.cities
['China']
`

Something like the following score could be interesting :
`[('United Kingdom',0.99), ('United States',0.56), ('Canada',0.45)]`

A score of confidence could help to avoid those results.

**Comment by WolfgangFahl** [comment]
How would you like to calculate the score? Currently there are a few possible strategies:

- use the population as an indicator e.g. Vienna Austria has a higher population as Vienna Illinois
- use the combination of fields as an indicator Wuhan China should limit the location as a grid search just in that area

Please note that the disambiguation is currently only possible with the Locator API.

**Comment by 0AlphaZero0** [comment]
I think a combination of fields should be the best approach.

**Comment by WolfgangFahl** [comment]
see also http://wiki.bitplan.com/index.php/Geograpy#Difference_in_Name.2FLabel

**Comment by WolfgangFahl** [comment]
#52 now addresses this - the default is to order by population. For our own use case we'll use a more sophisticated version and see what the likelyhood of a location is in our context given how often it is already in our corpus.
