### ISSUE TITLE
when can it supports text that written in chinese?

### ISSUE THREAD

**Issue by zhiyongLiu1114** [somnathrakshit/geograpy3#26]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by somnathrakshit** [comment]
We don't have any database of locations in Chinese right now. If you can share any, that would be great.

**Comment by 0AlphaZero0** [comment]
Geonames support Chinese language.

**Comment by zhiyongLiu1114** [comment]
> Geonames support Chinese language.

thank you very much. 
I have searched Geonames on github and  ipalaus/geonames was found, while it is developed by PHP, but I want some that develpoed by python so that I can use directly. it is really a pity

**Comment by zhiyongLiu1114** [comment]
> We don't have any database of locations in Chinese right now. If you can share any, that would be great.

I want to know if you want some data only consist of locations in Chinese or some data that used to train, which means not only include locations in Chinese but also other sentenses . if only locations in Chinese, please tell me the format , I'll try to find some

**Comment by WolfgangFahl** [comment]
Our wikidata source can be extended to chinese. So please specify your usecase with a scenario what you'd like to do. Best would be an example with a description of the situation in which you have the need, the action you'd like to perform and the expected result you'd like to see.

**Comment by zhiyongLiu1114** [comment]
> Our wikidata source can be extended to chinese. So please specify your usecase with a scenario what you'd like to do. Best would be an example with a description of the situation in which you have the need, the action you'd like to perform and the expected result you'd like to see. For discussion of the details it's also worthwhile to join the chat at https://gitter.im/geograpy3/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

When I send it a sentence(could be long), it will find all countries、cities and so on , and when there is only cities in a sentence, it can find out which country the city belongs to. I think there is no obvious changes compared to English

**Comment by zhiyongLiu1114** [comment]
> Our wikidata source can be extended to chinese. So please specify your usecase with a scenario what you'd like to do. Best would be an example with a description of the situation in which you have the need, the action you'd like to perform and the expected result you'd like to see. For discussion of the details it's also worthwhile to join the chat at https://gitter.im/geograpy3/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

Thanks very much

**Comment by WolfgangFahl** [comment]
Could you please specify a concrete scenario. What would be the chinese input and the expected output? A simple short scenario from which we can derive a test case will be sufficient.

**Comment by WolfgangFahl** [comment]
Version 0.2.0 has now an english label table derived from wikidata. Preparing a chinese label table would be possible now. Since there was no concrete scenario or acceptance criterion supplied I am closing the issue for now.
