### ISSUE TITLE
Are there any plans on using SpaCy instead of NLTK?

### ISSUE THREAD

**Issue by Guidofaassen** [somnathrakshit/geograpy3#33]
Currently NLTK is used for parsing the named entities. Some of the latest solutions use SpaCy as it has good performance and supports multiple languages.

**Comment by WolfgangFahl** [comment]
@Guidofaassen  thank you for your request. Indeed comparing SpaCy and NLTK makes sense. We might also investigate Weaviate.

What is your concrete usecase? If you specify your expectations I'd keep this issue open otherwise i'll close it and label it as a question

**Comment by WolfgangFahl** [comment]
Please also note that we are using google discussion now so we could continue this topic there.

**Comment by Guidofaassen** [comment]
No specific use case, just improving the performance of the entire product & adding languages. SpaCy has more recent models (with transformers, like BERT) and they also have support for other languages, like Dutch. NLTK does not have this option.
