### ISSUE TITLE
[BUG] Remove duplicate location entries from the raw city table 

### ISSUE THREAD

**Issue by tholzheim** [somnathrakshit/geograpy3#37]
Currently the raw city table contains duplicate entries such as the population values of multiple years resulting in multiple city entries.

**Comment by WolfgangFahl** [comment]
**Berlin example**
**query**
**query**
```sql
select * from cityLookup where label='Berlin' order by pop desc,regionName
```
**result**
| label   |   level | locationKind   | wikidataid   | name            |   geoNameId | regionId   | countryId   |             pop |      lat |      lon | partOfRegionId   | gndId     | regionName          | regionIso   |        regionPop |   regionLat |   regionLon | countryName              | countryIso   |   CountryLat |   CountryLon |
|---------|---------|----------------|--------------|-----------------|-------------|------------|-------------|-----------------|----------|----------|------------------|-----------|---------------------|-------------|------------------|-------------|-------------|--------------------------|--------------|--------------|--------------|
| Berlin  |       5 | City           | Q64          | Berlin          |     6547383 | Q64        | Q183        |     3.64483e+06 |  52.5167 |  13.3833 | Q183             | 4005728-8 | Berlin              | DE-BE       |      3.64483e+06 |     52.5167 |    13.3833  | Germany                  | DE           |      51      |      10      |
| Berlin  |       5 | City           | Q64          | Berlin          |     6547539 | Q64        | Q183        |     3.64483e+06 |  52.5167 |  13.3833 | Q183             | 4005728-8 | Berlin              | DE-BE       |      3.64483e+06 |     52.5167 |    13.3833  | Germany                  | DE           |      51      |      10      |
| Berlin  |       5 | City           | Q64          | Berlin          |     2950159 | Q64        | Q183        |     3.64483e+06 |  52.5167 |  13.3833 | Q183             | 4005728-8 | Berlin              | DE-BE       |      3.64483e+06 |     52.5167 |    13.3833  | Germany                  | DE           |      51      |      10      |
| Berlin  |       5 | City           | Q64          | Berlin          |     2950157 | Q64        | Q183        |     3.64483e+06 |  52.5167 |  13.3833 | Q183             | 4005728-8 | Berlin              | DE-BE       |      3.64483e+06 |     52.5167 |    13.3833  | Germany                  | DE           |      51      |      10      |
| Berlin  |       5 | City           | Q821199      | Berlin          |     5282244 | Q779       | Q30         | 19866           |  41.6139 | -72.7725 | Q54236           |           | Connecticut         | US-CT       |      3.59089e+06 |     41.6    |   -72.7     | United States of America | US           |      39.8282 |     -98.5795 |
| Berlin  |       5 | City           | Q821244      | Berlin          |     5083330 | Q759       | Q30         | 10051           |  44.4686 | -71.1839 | Q54447           |           | New Hampshire       | US-NH       |      1.33061e+06 |     44      |   -71.5     | United States of America | US           |      39.8282 |     -98.5795 |
| Berlin  |       5 | City           | Q1086827     | Berlin          |     4500771 | Q1408      | Q30         |  7588           |  39.7912 | -74.9291 | Q497810          |           | New Jersey          | US-NJ       |      8.95801e+06 |     40      |   -74.5     | United States of America | US           |      39.8282 |     -98.5795 |
| Berlin  |       5 | City           | Q1569850     | Berlin          |     5245497 | Q1537      | Q30         |  5524           |  43.9697 | -88.9486 | Q500880          |           | Wisconsin           | US-WI       |      5.77134e+06 |     44.5    |   -89.5     | United States of America | US           |      39.8282 |     -98.5795 |
| Berlin  |       5 | City           | Q1569850     | Berlin          |     5245497 | Q1537      | Q30         |  5524           |  43.9697 | -88.9486 | Q500891          |           | Wisconsin           | US-WI       |      5.77134e+06 |     44.5    |   -89.5     | United States of America | US           |      39.8282 |     -98.5795 |
| Berlin  |       5 | City           | Q3720748     | Berlin Township |     4500777 | Q1408      | Q30         |  5357           |  39.8071 | -74.9242 | Q497810          |           | New Jersey          | US-NJ       |      8.95801e+06 |     40      |   -74.5     | United States of America | US           |      39.8282 |     -98.5795 |
| Berlin  |       5 | City           | Q614184      | Berlin          |     4348460 | Q1391      | Q30         |  4485           |  38.3333 | -75.2167 | Q494072          |           | Maryland            | US-MD       |      6.04568e+06 |     39      |   -76.7     | United States of America | US           |      39.8282 |     -98.5795 |
| Berlin  |       5 | City           | Q524646      | Berlin          |     4930431 | Q771       | Q30         |  2866           |  42.3811 | -71.6375 | Q54093           |           | Massachusetts       | US-MA       |      6.79442e+06 |     42.3    |   -71.8     | United States of America | US           |      39.8282 |     -98.5795 |
| Berlin  |       5 | City           | Q821215      | Berlin          |     5108863 | Q1384      | Q30         |  1880           |  42.6833 | -73.3667 | Q156566          |           | New York            | US-NY       |      1.97958e+07 |     43      |   -75       | United States of America | US           |      39.8282 |     -98.5795 |
| Berlin  |       5 | City           | Q4892348     | Berlin          |             | Q1537      | Q30         |  1145           |  43.9681 | -88.9433 | Q500891          |           | Wisconsin           | US-WI       |      5.77134e+06 |     44.5    |   -89.5     | United States of America | US           |      39.8282 |     -98.5795 |
| Berlin  |       5 | City           | Q4892350     | Berlin          |     5245512 | Q1537      | Q30         |   945           |  45.0689 | -89.7933 | Q505848          |           | Wisconsin           | US-WI       |      5.77134e+06 |     44.5    |   -89.5     | United States of America | US           |      39.8282 |     -98.5795 |
| Berlin  |       5 | City           | Q142659      | Berlin          |     5147132 | Q1397      | Q30         |   898           |  40.5611 | -81.7944 | Q485650          |           | Ohio                | US-OH       |      1.16134e+07 |     40.5    |   -82.5     | United States of America | US           |      39.8282 |     -98.5795 |
| Berlin  |       5 | City           | Q2345711     | Berlin          |     4182096 | Q1428      | Q30         |   551           |  31.0675 | -83.6236 | Q113005          |           | Georgia             | US-GA       |      1.02149e+07 |     33      |   -83.5     | United States of America | US           |      39.8282 |     -98.5795 |
| Berlin  |       5 | City           | Q1930098     | Lincoln         |     4864742 | Q1546      | Q30         |   162           |  42.2625 | -92.6919 | Q119372          |           | Iowa                | US-IA       |      3.04636e+06 |     42      |   -93       | United States of America | US           |      39.8282 |     -98.5795 |
| Berlin  |       5 | City           | Q821229      | Berlin          |     5058265 | Q1207      | Q30         |    34           |  46.3783 | -98.4878 | Q48891           |           | North Dakota        | US-ND       | 756927           |     47.5    |  -100.5     | United States of America | US           |      39.8282 |     -98.5795 |
| Berlin  |       5 | City           | Q4892339     | Berlin          |     4047787 | Q173       | Q30         |                 |  34.1814 | -86.7422 | Q188204          |           | Alabama             | US-AL       |      4.85898e+06 |     32.7    |   -86.7     | United States of America | US           |      39.8282 |     -98.5795 |
| Berlin  |       5 | City           | Q20144232    | Berlín          |     8922112 | Q60123     | Q96         |                 |  16.3094 | -93.4272 | Q20735271        |           | Chiapas             | MX-CHP      |      5.21791e+06 |     16.41   |   -92.4086  | Mexico                   | MX           |      23      |    -102      |
| Berlin  |       5 | City           | Q4892343     | Berlin          |             | Q130840    | Q258        |                 | -32.874  |  27.588  | Q1002006         |           | Eastern Cape        | ZA-EC       |      6.67659e+06 |    -32      |    27       | South Africa             | ZA           |     -29      |      24      |
| Berlin  |       5 | City           | Q2504681     | Berlin          |     4233627 | Q1204      | Q30         |                 |  39.7569 | -89.9033 | Q1204            |           | Illinois            | US-IL       |      1.286e+07   |     40.0003 |   -89.2503  | United States of America | US           |      39.8282 |     -98.5795 |
| Berlin  |       5 | City           | Q17509488    | Berlin          |             | Q1558      | Q30         |                 |  37.9214 | -94.8961 | Q1558            |           | Kansas              | US-KS       |      2.91164e+06 |     38.5    |   -98       | United States of America | US           |      39.8282 |     -98.5795 |
| Berlin  |       5 | City           | Q821190      | Berlin          |     4283975 | Q1603      | Q30         |                 |  38.6948 | -84.1624 | Q491945          |           | Kentucky            | US-KY       |      4.42509e+06 |     37.5    |   -85       | United States of America | US           |      39.8282 |     -98.5795 |
| Berlin  |       5 | City           | Q4892354     | Berlin          |     4530350 | Q1649      | Q30         |                 |  35.4506 | -99.6253 | Q489332          |           | Oklahoma            | US-OK       |      3.91134e+06 |     35.5    |   -98       | United States of America | US           |      39.8282 |     -98.5795 |
| Berlin  |       5 | City           | Q1130950     | Berlin          |     4556518 | Q1400      | Q30         |                 |  39.9214 | -78.95   | Q490908          |           | Pennsylvania        | US-PA       |      1.28025e+07 |     41      |   -77.5     | United States of America | US           |      39.8282 |     -98.5795 |
| Berlin  |       5 | City           | Q1130950     | Berlin          |     4556518 | Q1400      | Q30         |                 |  39.9206 | -78.9578 | Q490908          |           | Pennsylvania        | US-PA       |      1.28025e+07 |     41      |   -77.5     | United States of America | US           |      39.8282 |     -98.5795 |
| Berlin  |       5 | City           | Q12303254    | Berlin          |             | Q26061     | Q35         |                 |  55.4634 |  10.047  | Q21140           |           | Southern Denmark    | DK-83       |      1.22389e+06 |     55.3333 |     9.66667 | Denmark                  | DK           |      56      |      10      |
| Berlin  |       5 | City           | Q21196360    | Berlin          |             | Q1439      | Q30         |                 |  30.1714 | -96.4458 | Q156444          |           | Texas               | US-TX       |      2.74691e+07 |     31      |  -100       | United States of America | US           |      39.8282 |     -98.5795 |
| Berlin  |       5 | City           | Q582242      | Berlín          |     3587266 | Q1122748   | Q792        |                 |  13.5    | -88.5333 | Q67221821        |           | Usulután Department | SV-US       | 464883           |     13.4333 |   -88.5333  | El Salvador              | SV           |      13.6689 |     -88.8661 |
| Berlin  |       5 | City           | Q582242      | Berlín          |     3587266 | Q1122748   | Q792        |                 |  13.5    | -88.5333 | Q1122748         |           | Usulután Department | SV-US       | 464883           |     13.4333 |   -88.5333  | El Salvador              | SV           |      13.6689 |     -88.8661 |
| Berlin  |       5 | City           | Q821245      | Berlin          |             | Q16551     | Q30         |                 |  44.2094 | -72.604  | Q505380          |           | Vermont             | US-VT       | 626042           |     44      |   -72.7     | United States of America | US           |      39.8282 |     -98.5795 |
| Berlin  |       5 | City           | Q664745      | Berlin          |     4798708 | Q1371      | Q30         |
