### ISSUE TITLE
add python 3.9 checks to CI

### ISSUE THREAD

**Issue by WolfgangFahl** [somnathrakshit/geograpy3#46]
Currently 3.6 to 3.8 is checked. 3.9 is available and stable and would IMHO be a good addition to the CI

**Comment by somnathrakshit** [comment]
Done via Commit #6c89c5c

**Comment by somnathrakshit** [comment]
Done via commit [6c89c5c](https://github.com/somnathrakshit/geograpy3/commit/6c89c5c0e7d828e78581aa43b9a8518b7cdb8995)
