### ISSUE TITLE
Signapore Michigan  in CityLookup but Singapore, Singapore is not ...

### ISSUE THREAD

**Issue by WolfgangFahl** [somnathrakshit/geograpy3#55]
[Singapore Michigan](https://www.wikidata.org/wiki/Q7522845) is a ghost town and former settlement - these might rather be ignored

**Comment by WolfgangFahl** [comment]
````sql
select  cl.wikidataid,label,name,pop,regionIso,regionName,countryIso,countryName,gndId,geoNameId,lat,lon from 
city_labels l 
join CityLookup cl on l.wikidataid=cl.wikidataid
where l.label in ('St. Petersburg','Singapore')
```
| wikidataid   | label          | name             |              pop | regionIso   | regionName       | countryIso   | countryName              | gndId     |   geoNameId |      lat |      lon |
|--------------|----------------|------------------|------------------|-------------|------------------|--------------|--------------------------|-----------|-------------|----------|----------|
| Q656         | St. Petersburg | Saint Petersburg |      5.38434e+06 | RU-SPE      | Saint Petersburg | RU           | Russia                   | 4267026-3 |      498817 |  59.95   |  30.3167 |
| Q49236       | St. Petersburg | St. Petersburg   | 253693           | US-FL       | Florida          | US           | United States of America | 4251544-0 |     4171563 |  27.7731 | -82.64   |
| Q7522845     | Singapore      | Singapore        |                  | US-MI       | Michigan         | US           | United States of America |           |             |  42.6778 | -86.21   |
| Q1187352     | St. Petersburg | St. Petersburg   |                  | US-PA       | Pennsylvania     | US           | United States of America |           |     5210484 |  41.1617 | -79.6528 |
| Q1187352     | St. Petersburg | St. Petersburg   |                  | US-PA       | Pennsylvania     | US           | United States of America |           |     5210484 |  41.1617 | -79.6542 |
| Q334         | Singapore      | Singapore        |      5.88893e+06 | SG          | Singapore

**Comment by WolfgangFahl** [comment]
https://www.wikidata.org/wiki/Q334 is a city state
https://www.wikidata.org/wiki/Q133442
so we might need to add a query for the city states as a separate "region" Json file

**Comment by tholzheim** [comment]
The [city-states](https://www.wikidata.org/wiki/Q133442) are now included in the RegionManager. 
By querying the Cities by region as in https://github.com/somnathrakshit/geograpy3/blob/62856f8a2946b9bde1c91409f54cf3bb76684c40/tests/testCachingCitiesByRegion.py#L73 the [city-states](https://www.wikidata.org/wiki/Q133442) are than also added as cities (additionally with the municipalities of the city)

### SPARQL Query for all [city-states](https://www.wikidata.org/wiki/Q133442)
```sparql
# get a list of city states
# for geograpy3 library
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>
SELECT DISTINCT ?countryId (?cityStateQ as ?wikidataid) ?name ?iso ?pop ?coord
WHERE
{
  # all citiy states
  ?cityStateQ wdt:P31 wd:Q133442 .
  ?cityStateQ rdfs:label ?name filter (lang(?name) = "en").
  { 
    SELECT ?cityStateQ (max(?isoCode) as ?iso) (max(?populationValue) as ?pop) (max(?locationValue) as ?coord)
    WHERE {
      ?cityStateQ wdt:P300|wdt:P297 ?isoCode.
      # get the population
      # https://www.wikidata.org/wiki/Property:P1082
      OPTIONAL {
        ?cityStateQ wdt:P1082 ?populationValue
      } 
      # get the location
      # https://www.wikidata.org/wiki/Property:P625
      OPTIONAL {
        ?cityStateQ wdt:P625 ?locationValue. 
       }
    } GROUP BY ?cityStateQ
  }
  OPTIONAL { 
    ?cityStateQ wdt:P17 ?countryId.
  }
} ORDER BY ?iso
```
[Try it!](https://query.wikidata.org/#%23%20get%20a%20list%20of%20city%20states%0A%23%20for%20geograpy3%20library%0APREFIX%20rdfs%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0APREFIX%20wd%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fentity%2F%3E%0APREFIX%20wdt%3A%20%3Chttp%3A%2F%2Fwww.wikidata.org%2Fprop%2Fdirect%2F%3E%0APREFIX%20wikibase%3A%20%3Chttp%3A%2F%2Fwikiba.se%2Fontology%23%3E%0ASELECT%20DISTINCT%20%3FcountryId%20%28%3FcityStateQ%20as%20%3Fwikidataid%29%20%3Fname%20%3Fiso%20%3Fpop%20%3Fcoord%0AWHERE%0A%7B%0A%20%20%23%20all%20citiy%20states%0A%20%20%3FcityStateQ%20wdt%3AP31%20wd%3AQ133442%20.%0A%20%20%3FcityStateQ%20rdfs%3Alabel%20%3Fname%20filter%20%28lang%28%3Fname%29%20%3D%20%22en%22%29.%0A%20%20%7B%20%0A%20%20%20%20SELECT%20%3FcityStateQ%20%28max%28%3FisoCode%29%20as%20%3Fiso%29%20%28max%28%3FpopulationValue%29%20as%20%3Fpop%29%20%28max%28%3FlocationValue%29%20as%20%3Fcoord%29%0A%20%20%20%20WHERE%20%7B%0A%20%20%20%20%20%20%3FcityStateQ%20wdt%3AP300%7Cwdt%3AP297%20%3FisoCode.%0A%20%20%20%20%20%20%23%20get%20the%20population%0A%20%20%20%20%20%20%23%20https%3A%2F%2Fwww.wikidata.org%2Fwiki%2FProperty%3AP1082%0A%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%3FcityStateQ%20wdt%3AP1082%20%3FpopulationValue%0A%20%20%20%20%20%20%7D%20%0A%20%20%20%20%20%20%23%20get%20the%20location%0A%20%20%20%20%20%20%23%20https%3A%2F%2Fwww.wikidata.org%2Fwiki%2FProperty%3AP625%0A%20%20%20%20%20%20OPTIONAL%20%7B%0A%20%20%20%20%20%20%20%20%3FcityStateQ%20wdt%3AP625%20%3FlocationValue.%20%0A%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%20GROUP%20BY%20%3FcityStateQ%0A%20%20%7D%0A%20%20OPTIONAL%20%7B%20%0A%20%20%20%20%3FcityStateQ%20wdt%3AP17%20%3FcountryId.%0A%20%20%7D%0A%7D%20ORDER%20BY%20%3Fiso)
Used in https://github.com/somnathrakshit/geograpy3/blob/ba60d6e4b37e665205b2bc312085f0372053c620/geograpy/wikidata.py#L299

**Comment by WolfgangFahl** [comment]
see #70
