### ISSUE TITLE
Similarity matching is too error prone

### ISSUE THREAD

**Issue by tholzheim** [somnathrakshit/geograpy3#56]
The similarity matching might need to be adjusted to avoid identifying _United States_ as region 

`region_match("United States", "United States Minor Outlying Islands")`  is evaluated to true 
(region_match()→fuzzy_match()→jaro_winkler_similarity() with a max distance threshold of 0.8)

**Comment by WolfgangFahl** [comment]
I think we should make the fuzzy match optional and show some useful usecases for it.

**Comment by WolfgangFahl** [comment]
see #70
