### ISSUE TITLE
Make docs available via release process

### ISSUE THREAD

**Issue by WolfgangFahl** [somnathrakshit/geograpy3#6]
scripts/doc already does some basic work but might need some love e.g. fixing the error

WARNING: autodoc: failed to import module 'setup'; the following exception was raised:
Traceback (most recent call last):
  File "/Users/wf/Documents/pyworkspace/geograpy3/setup.py", line 5, in <module>
    with open('README.md', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/wf/Library/Python/3.8/lib/python/site-packages/sphinx/ext/autodoc/importer.py", line 66, in import_module
    return importlib.import_module(modname)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/wf/Documents/pyworkspace/geograpy3/setup.py", line 9, in <module>
    long_description = open('README.md').read()
FileNotFoundError: [Errno 2] No such file or directory: 'README.md'

and linking back to the pypi information. The result might also show up in readthedocs.

**Comment by somnathrakshit** [comment]
Deployed RTD docs using netlify. Coomit cc81b71ea, 2ffc0442 and 7ed8ba8

**Comment by somnathrakshit** [comment]
Current docs: https://geograpy3.netlify.app/

**Comment by WolfgangFahl** [comment]
That's a good first step.

I'd prefer a full automation as the doc script does instead of the having the redundant rst files in the repository. 
`git pull
remote: Enumerating objects: 49, done.
remote: Counting objects: 100% (46/46), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 35 (delta 18), reused 34 (delta 17), pack-reused 0
Entpacke Objekte: 100% (35/35), 5.42 KiB | 252.00 KiB/s, Fertig.
Von https://github.com/somnathrakshit/geograpy3
   35fae85..524d982  master     -> origin/master
Aktualisiere 35fae85..524d982
Fast-forward
 .github/workflows/deploy-docs.yml |  6 +--
 .gitignore                        |  3 +-
 .readthedocs.yml                  | 23 ++++++++++++
 docs/source/Makefile              | 20 ++++++++++
 docs/source/conf.py               | 77 +++++++++++++++++++++++++++++++++++++++
 docs/source/geograpy.rst          | 45 +++++++++++++++++++++++
 docs/source/index.rst             | 23 ++++++++++++
 docs/source/make.bat              | 35 ++++++++++++++++++
 docs/source/setup.rst             |  7 ++++
 docs/source/tests.rst             | 29 +++++++++++++++
 requirements.txt                  |  1 +
 setup.py                          |  6 ++-
 12 files changed, 268 insertions(+), 7 deletions(-)
 create mode 100644 .readthedocs.yml
 create mode 100644 docs/source/Makefile
 create mode 100644 docs/source/conf.py
 create mode 100644 docs/source/geograpy.rst
 create mode 100644 docs/source/index.rst
 create mode 100644 docs/source/make.bat
 create mode 100644 docs/source/setup.rst
 create mode 100644 docs/source/tests.rst`

**Comment by somnathrakshit** [comment]
Readthedocs is working now.

**Comment by WolfgangFahl** [comment]
I am closing this - if there are details followup issues let's open a new ticket
