### ISSUE TITLE
[BUG] Cities are linked to Netherlands, not to Kingdom of the Netherlands

### ISSUE THREAD

**Issue by LokiLuciferase** [somnathrakshit/geograpy3#62]
Hi, I am experiencing the following issue:

**Describe the bug**
Most Dutch cities appear to be linked to the country "Netherlands" (wikidataid Q55) which, as Wikipedia tells me, is a constituent country of the sovereign state of "Kingdom of the Netherlands" (wikidataid Q29999). If I am not mistaken, this relationship is similar to the one where "England" is a constituent country of the "United Kingdom" (Q145). However, in the former case, almost all (but not all!) cities appear to be linked to the constituent country, while in the latter case all cities are correctly linked to the sovereign state (Q145).

**To Reproduce**
```python3
#!/usr/bin/env python3

from geograpy import Locator
l = Locator()
l.populate_db()
assert l.is_a_country('Kingdom of the Netherlands')  # succeeds
assert l.is_a_country(l.aliases.get('Netherlands', 'Netherlands'))  # fails...
assert l.locateCity(['Amsterdam']).country.name == 'Netherlands'  # succeeds...
```
Manually inspecting the `locations.db` database shows that most cities and all regions are linked to Q55, not Q29999:

```
sqlite> select countries.wikidataid, countries.name, count(countries.name) from countries join cities on countries.wikidataid = cities.countryId where countries.name like '%etherlands%' group by countries.wikidataid;
Q29999|Kingdom of the Netherlands|42
Q55|Netherlands|28289
```
```
sqlite> select countries.wikidataid, countries.name, count(countries.name) from countries join regions on countries.wikidataid = regions.countryId where countries.name like '%etherlands%' group by countries.wikidataid;
Q55|Netherlands|14
```

**Expected behavior**
Cities and regions should be linked to the sovereign state and not to a constituent country. The library should then probably account for the state's extremely common alias ("(the) Netherlands") to mean the whole state, not just the constituent country.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python Version: 3.9
 - geograpy3 Version: latest from PyPI (0.2.2) and the latest version of the locations.db downloaded at runtime

thanks and best regards,
Lukas

**Comment by WolfgangFahl** [comment]
see #70
