### ISSUE TITLE
[BUG] Multiple false positives on quite simple text

### ISSUE THREAD

**Issue by adulau** [somnathrakshit/geograpy3#64]
**Describe the bug**

With the following text:

~~~~
Wholesale Laminator of high quality with a discount from our factory. Our factory called NINGBO OFITECH BUSINESS MACHINES CO., LTD., which is one of the manufacturers and suppliers from China. Laminator made in China is GS,CE,UL certified, with RoHs, Reach test report. Our newest products never go out of fashion can be purchased and we welcome your asking quotation. NINGBO OFITECH BUSINESS MACHINES CO., LTD. is a professional China laminators Manufacturers and China laminators suppliers. Our factory which manufactures Laminator. Established in 2001, Ofitech has been a leading manufacturer and marketer in document and data security shredder in China.We develop, manufacture and distribute full range shredders, from personal use to commercial level for security destruction of paper documents, credit cards, CDs, and microchips.
https://www.ofitech-shredder.com/

~~~~

**To Reproduce**
1. use `geograpy.get_geoPlace_context` with the text parameter.
The locations have been found

~~~~json
{"geoloc:countries": ["People's Republic of China", "Japan", "United States of America", "India", "Mexico"], 
"geoloc:cities": ["China"], 
"geoloc:other": ["Reach", "China.We"]}
~~~~

**Expected behavior**

I was expecting to see only China (which is correctly found) but not the other countries.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python 3.8.10

**Comment by WolfgangFahl** [comment]
@adulau  Thanks for pointing out this mismatch between your expectations and the result via the API you choose. 

We are not intending to improve the "old" API any more so you might want to try the new lookup API and be more specific about what results you'd expect.

**Comment by adulau** [comment]
Thanks. Maybe I missed this in the documentation, what's the new and deprecated API?

**Comment by WolfgangFahl** [comment]
@adulau see https://github.com/somnathrakshit/geograpy3/blob/master/tests/test_locator.py - the refactoring is not finished yet but the idea is to e.g. input "Cambridge, MA" and getback Cambridge, Massachusetts, United States of America with the corresponding Wikidata IDs. The step to extract "Cambridge MA" as a natural language processing step is not so much in the focus of geograpy any more. For the ConfIDent project we are e.g creating a special lookup parser that uses a dictionary (with only relevant countries, region and cities) see https://github.com/WolfgangFahl/ConferenceCorpus/blob/main/corpus/location.py and https://github.com/WolfgangFahl/ConferenceCorpus/tree/main/ptp and https://github.com/WolfgangFahl/ConferenceCorpus/tree/main/resources

**Comment by WolfgangFahl** [comment]
see #70
