### ISSUE TITLE
:curacao:  Please support "Curacao" :pray: 

### ISSUE THREAD

**Issue by adriens** [somnathrakshit/geograpy3#68]
Actually when I get the following input  `Curacao`, it is not recognized and get a null list for `places.countries`

```python
places = geograpy.get_geoPlace_context(text = 'Curacao')
```

:bulb: Maybe is it due to the fact the input string has no accent (see [Curaçao](https://en.wikipedia.org/wiki/Cura%C3%A7ao))

**Comment by WolfgangFahl** [comment]
See #70
