### ISSUE TITLE
[BUG] command not found: geograpy-nltk

### ISSUE THREAD

**Issue by aa-dank** [somnathrakshit/geograpy3#73]
**Describe the bug**
Successfully installed geography3 in venv virtual environment. Cannot run geograpy-nltk

**To Reproduce**

-     activate python environment
-     Attempted uninstallation of geograpy3 version 0.2.7 from a virtual environment (venv) located at a specific path on macOS. Uninstallation was successful.
-     Reinstalled geograpy3 version 0.2.7 in the same venv. Dependencies such as newspaper3k, nltk, jellyfish, numpy, etc., were already satisfied. Installation completed successfully.
-     Tried executing the geograpy-nltk command in the terminal (zsh) with the venv activated. Received an error: "command not found: geograpy-nltk".

**Environment (please complete the following information):**
 - OS: MacOS 13.6.1
 - Apple Silicon
 - Python 3.10.4

**Additional context**
geograpy-nltk not in the venv bin directory if that is where it is supposed to be.
I also attempted to use geograpy3 in a google colab notebook and ran into the same issue attempting to install it there.

**Comment by WolfgangFahl** [comment]
An update of geograpy is due to the new @lod_storable annotatin in pyLoDStorage in the upcoming days anyway - I intend to work on this while at it. Please stay tuned for a few weeks.

**Comment by josuemy** [comment]
Did this fix the issue? I'm still not able to run the `geograpy-nltk` script. I still get `zsh: command not found: geograpy-nltk` and I have the latest version of geograpy3 installed
